### ISSUE TITLE
mismatched types

### ISSUE THREAD

**Issue by bengisupinar** [dfinity/experimental-minting-tool#2]
Hello, I am trying to use tool. But, when I run "cargo install --git https://github.com/dfinity/experimental-minting-tool" command it gives error. How can I fix this. 
![Screen Shot 2022-09-07 at 18 14 30](https://user-images.githubusercontent.com/32142395/188914877-c1ea2985-9237-4f85-9086-c48418af28a1.png)

Rust version:
![image](https://user-images.githubusercontent.com/32142395/188915172-eed5f2ad-1c13-4f19-a0ff-3beeb56b51ce.png)

**Comment by alperencesur** [comment]
Yes I have same issue!

**Comment by sibukixxx** [comment]
```
// use candid::Principal;
use ic_agent::export::Principal;
```

**Comment by uguraltinsoy** [comment]
i have the same problem

**Comment by AuroraLantean** [comment]
Same here! Bugs!!!

**Comment by adamspofford-dfinity** [comment]
Fixed in d6e015a.
